# Generated by Django 6.0.5 on 2026-05-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_celery_task_config_and_run"),
    ]

    operations = [
        migrations.RenameField(
            model_name="celerytaskconfig",
            old_name="enabled",
            new_name="schedule_enabled",
        ),
        migrations.AddField(
            model_name="celerytaskconfig",
            name="execution_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
