# Generated by Django 6.0.5 on 2026-05-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_rename_enabled_celerytaskconfig_schedule_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytaskconfig',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
