# Generated by Django 6.0.5 on 2026-05-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_celerytaskconfig_parameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryTaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level", models.PositiveSmallIntegerField()),
                ("level_name", models.CharField(max_length=16)),
                ("logger_name", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("traceback_text", models.TextField(blank=True, default="")),
                ("process", models.PositiveIntegerField(blank=True, null=True)),
                ("thread", models.PositiveBigIntegerField(blank=True, null=True)),
                ("pathname", models.CharField(blank=True, default="", max_length=1024)),
                ("lineno", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="panel.celerytaskrun",
                    ),
                ),
            ],
            options={
                "db_table": "panel_celery_task_log",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["run", "created_at"],
                        name="panel_celer_run_id_87dfad_idx",
                    ),
                    models.Index(fields=["level"], name="panel_celer_level_2c2dc1_idx"),
                ],
            },
        ),
    ]
