# Generated by Django 6.0.2 on 2026-02-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Имя ресурса')),
                ('path', models.TextField(blank=True, default=None, null=True, verbose_name='Путь к файлу')),
                ('metadata', models.JSONField(blank=True, default=None, null=True, verbose_name='Метаданные')),
                ('deprecated', models.BooleanField(default=False, verbose_name='Ресурс устарел')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'db_table': 'setting',
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mimetype', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Расширение файла')),
                ('url', models.TextField(blank=True, default=None, null=True, verbose_name='URL источника на сайте')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата обнаружения версии')),
                ('last_changed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата изменения по данным сайта')),
                ('hashsum', models.CharField(max_length=255, verbose_name='SHA-256 хэш содержимого файла')),
                ('resource', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='common.resource', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Версия файла',
                'verbose_name_plural': 'Версии файлов',
                'db_table': 'file_version',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название тега')),
                ('category', models.CharField(max_length=200, verbose_name='Название категории тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tag',
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_name_category')],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='common.tag', verbose_name='Теги'),
        ),
    ]
