# Generated by Django 6.0.5 on 2026-05-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_alter_fileversion_hashsum"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableFileImport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "file_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_imports",
                        to="common.fileversion",
                        verbose_name="Версия файла",
                    ),
                ),
            ],
            options={
                "verbose_name": "Импорт файла расписания",
                "verbose_name_plural": "Импорты файлов расписания",
                "db_table": "timetable_file_import",
                "indexes": [
                    models.Index(
                        fields=["file_version", "status"],
                        name="tfi_version_status_idx",
                    )
                ],
            },
        ),
    ]
