# Generated by Django 6.0.5 on 2026-05-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_timetablefileimport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("body", models.TextField(verbose_name="Text")),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Title (English)",
                    ),
                ),
                (
                    "body_en",
                    models.TextField(
                        blank=True, default="", verbose_name="Text (English)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("danger", "Danger"),
                            ("warning", "Warning"),
                            ("success", "Success"),
                            ("notice", "Notice"),
                        ],
                        default="notice",
                        max_length=16,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Enabled"),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, verbose_name="Show only in admin panel"
                    ),
                ),
                (
                    "is_dismissible",
                    models.BooleanField(default=True, verbose_name="User can close"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Starts at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "db_table": "alert",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["is_enabled", "is_admin", "starts_at", "expires_at"],
                        name="alert_active_idx",
                    )
                ],
            },
        ),
    ]
