# Generated by Django 6.0.5 on 2026-05-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_alert"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Оповещение",
                "verbose_name_plural": "Оповещения",
            },
        ),
        migrations.AlterField(
            model_name="alert",
            name="body",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="alert",
            name="body_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Текст (английский)"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="category",
            field=models.CharField(
                choices=[
                    ("danger", "Критическое"),
                    ("warning", "Предупреждение"),
                    ("success", "Успех"),
                    ("notice", "Уведомление"),
                ],
                default="notice",
                max_length=16,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="alert",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата окончания показа",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="is_admin",
            field=models.BooleanField(
                default=False, verbose_name="Показывать только в панели администратора"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="is_dismissible",
            field=models.BooleanField(
                default=True, verbose_name="Пользователь может закрыть"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="Включено"),
        ),
        migrations.AlterField(
            model_name="alert",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Дата начала показа"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="alert",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Заголовок (английский)",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="timetablefileimport",
            name="error",
            field=models.TextField(blank=True, default="", verbose_name="Ошибка"),
        ),
        migrations.AlterField(
            model_name="timetablefileimport",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AlterField(
            model_name="timetablefileimport",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="Метаданные"),
        ),
        migrations.AlterField(
            model_name="timetablefileimport",
            name="result",
            field=models.JSONField(blank=True, default=dict, verbose_name="Результат"),
        ),
        migrations.AlterField(
            model_name="timetablefileimport",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="timetablefileimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает импорта"),
                    ("imported", "Импортирован"),
                    ("failed", "Ошибка импорта"),
                    ("skipped", "Пропущен"),
                ],
                default="pending",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
    ]
