# Generated by Django 6.0.5 on 2026-05-29 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_alter_alert_options_alter_alert_body_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="abstractday",
            index=models.Index(fields=["day_number"], name="abstractday_number_idx"),
        ),
        migrations.AddIndex(
            model_name="abstractday",
            index=models.Index(fields=["name"], name="abstractday_name_idx"),
        ),
        migrations.AddIndex(
            model_name="abstractevent",
            index=models.Index(
                fields=["schedule", "abstract_day", "time_slot", "holds_on_date"],
                name="ae_schedule_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="abstracteventchanges",
            index=models.Index(fields=["is_exported"], name="ae_changes_exported_idx"),
        ),
        migrations.AddIndex(
            model_name="abstracteventchanges",
            index=models.Index(fields=["datemodified"], name="ae_changes_modified_idx"),
        ),
        migrations.AddIndex(
            model_name="daydateoverride",
            index=models.Index(
                fields=["department", "day_source"], name="dayoverride_dept_source_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="department_code_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["shortname"], name="department_shortname_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["name", "shortname", "code"], name="department_identity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="event_date_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_event_overriden"], name="event_overriden_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_event_canceled"], name="event_canceled_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["abstract_event", "is_event_overriden"],
                name="event_abs_overriden_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["date", "time_slot_override"], name="event_date_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcancel",
            index=models.Index(
                fields=["department", "date"], name="eventcancel_dept_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventkind",
            index=models.Index(fields=["name"], name="eventkind_name_idx"),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(fields=["name"], name="eventparticipant_name_idx"),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(fields=["role"], name="eventparticipant_role_idx"),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(
                fields=["is_group"], name="eventparticipant_is_group_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(
                fields=["name", "department"], name="eventparticipant_identity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventplace",
            index=models.Index(fields=["room"], name="eventplace_room_idx"),
        ),
        migrations.AddIndex(
            model_name="eventplace",
            index=models.Index(
                fields=["building", "room"], name="eventplace_building_room_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileversion",
            index=models.Index(
                fields=["-timestamp", "-id"], name="fileversion_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileversion",
            index=models.Index(
                fields=["resource", "-last_changed", "-timestamp"],
                name="fv_resource_latest_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="organization_name_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["deprecated", "-last_update"],
                name="resource_status_updated_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["name"], name="resource_name_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["path", "name"], name="resource_path_name_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["status"], name="schedule_status_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["metadata", "schedule_template", "status"],
                name="schedule_identity_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schedulemetadata",
            index=models.Index(
                fields=["years", "course", "semester"], name="schedule_meta_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduletemplate",
            index=models.Index(
                fields=["metadata", "department"], name="sch_tmpl_meta_dept_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduletemplatemetadata",
            index=models.Index(
                fields=["faculty", "scope"], name="sch_tmpl_meta_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["name"], name="subject_name_idx"),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(fields=["alt_name"], name="timeslot_alt_name_idx"),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(fields=["start_time"], name="timeslot_start_time_idx"),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["alt_name", "start_time", "end_time"],
                name="timeslot_lookup_idx",
            ),
        ),
    ]
