# Generated by Django 6.0.7 on 2026-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_schedule_accuracy_warning_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Версия заархивирована'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла на диске'),
        ),
    ]
