CLIENT_FILTER_OPTIONS_CACHE_KEY = "client:schedule:filter-options:v1"
CLIENT_FILTER_OPTIONS_CACHE_TIMEOUT_SECONDS = 2 * 60 * 60
CLIENT_MAX_FILTERED_EVENTS = 250

TIMETABLE_FILE_DOWNLOAD_TIMEOUT_SECONDS = 30
TIMETABLE_MAX_DOWNLOAD_BYTES = 2 * 1024 * 1024
TIMETABLE_WEB_REQUEST_TIMEOUT_SECONDS = 10
