"""
Django settings for timetable_project project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# VIRTUALENV_PATH = Path('C:\\Users\\Влад\\VirtualBox VMs\\tesle')
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
TEMP_DIR = BASE_DIR / "temp"
DATA_STORAGE_DIR = STATIC_ROOT / "files"
VIS_PATH = DATA_STORAGE_DIR / "ВИЗ"
GOOGLE_AUTH_FILE = BASE_DIR / "auth" / "google_drive_auth.json"
# LIBREOFFICE_EXE = "libreoffice"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#q+2%evpem%e=)1^w$&3=zs2x6k608&sd^0o+@nr(676xhz_6x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "127.0.0.1:81"]
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000", "http://127.0.0.1:81"]

# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_apscheduler",
    "timetable",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CSRF_COOKIE_SECURE = True

ROOT_URLCONF = "timetable_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "timetable_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "timetable",  # Укажи имя своей базы данных
        "USER": "root",  # Укажи своего пользователя MySQL
        "PASSWORD": "root",  # Укажи пароль для подключения
        "HOST": "127.0.0.1",  # Или другой хост, если не локальный сервер
        "PORT": "3306",  # Стандартный порт для MySQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_URL = "admin_login"
LOGIN_REDIRECT_URL = "admin_panel"


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Путь для директории логов
LOG_DIR = BASE_DIR / "logs"
# Убедимся, что директория существует
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Логирование

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        # DEBUG файл с датой в имени
        "debug_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_DIR / "debug.log",
            "when": "midnight",  # ротация каждый день
            "interval": 1,
            "backupCount": 7,  # хранить 7 дней
            "formatter": "verbose",
        },
        # INFO файл с датой в имени
        "info_file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_DIR / "info.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 30,  # хранить 30 дней
            "formatter": "simple",
        },
        # ERROR файл с датой в имени
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_DIR / "errors.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 90,  # хранить 90 дней
            "formatter": "verbose",
        },
        # Консоль для разработки
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["info_file", "error_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "timetable": {
            "handlers": ["debug_file", "info_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "": {  # Корневой логгер
            "handlers": ["info_file", "error_file"],
            "level": "INFO",
        },
    },
}
